### ISSUE TITLE
Exception on Start Measure

### ISSUE THREAD

**Issue by volodymyrdovhan** [WIDE-Services/ws_block_course_statistics_u#1]
Hello,
I received an error when tried to Start Measure the course:

![image](https://github.com/user-attachments/assets/7cac4c07-1757-4305-9a7d-5fa912fd9ab2)

Thank you

**Comment by dorispanos** [comment]
Yeah didnt have that error but i change the structure of external to a folder with proper namespace and calling the externallib->
![image](https://github.com/user-attachments/assets/6ef688e9-ce77-416c-89f0-5ecec3fe088a)
I believe no errors will pop up this time ->
![image](https://github.com/user-attachments/assets/319105d3-7a3e-4bae-ba2f-0cd5f7d0702f)
