### ISSUE TITLE
Plugin Description issue

### ISSUE THREAD

**Issue by volodymyrdovhan** [WIDE-Services/ws_block_course_statistics_u#2]
Hello, 
in Plugin description I found instructions:

Locating the Plugin

- Navigate to Site Administration > Manage Courses and Categories.
- The plugin will be displayed in the right panel as a block.

But the block can be added only on the course page:
![image](https://github.com/user-attachments/assets/8e4f7e30-0789-4d57-94e0-a05ac7408409)

**Comment by dorispanos** [comment]
Yes i have updated the documentation. The plugin is added in a course page.
![image](https://github.com/user-attachments/assets/fdd47feb-f97d-46be-8cd1-f67feeec90c2)
