### ISSUE TITLE
Missed language strings in Privacy API

### ISSUE THREAD

**Issue by volodymyrdovhan** [WIDE-Services/ws_block_course_statistics_u#3]
Hello,
1. I found missed language strings for the Privacy API description:
![image](https://github.com/user-attachments/assets/f5cbba61-6495-4e7d-94b6-a381a1141666)

2. Please validate Privacy API implementation with CLI scripts/tools https://moodledev.io/docs/4.5/apis/subsystems/privacy/utils or unit tests.

3. If your plugin does not store any files - then you don't need to change files in Privacy class:
![image](https://github.com/user-attachments/assets/fcf42da8-4959-4db6-bf2b-8cc6d56dfd7e)
Or if you are going to delete files - then use File API: https://moodledev.io/docs/4.5/apis/subsystems/files#delete-file

Thank you

**Comment by dorispanos** [comment]
i have added the missing strings and removed the file, I dont use any files in my plugin.
![image](https://github.com/user-attachments/assets/54b86a7e-4ca0-41b5-9a94-2a39640a002b)
