### ISSUE TITLE
Missing Context and Capability Validation in External Service

### ISSUE THREAD

**Issue by volodymyrdovhan** [WIDE-Services/ws_block_course_statistics_u#4]
Hello,
I found an issue with missing capabilities and context validation in the external services.

Please review the documentation for more details:
[Context and Capability Checks - Moodle External Services](https://moodledev.io/docs/4.5/apis/subsystems/external/writing-a-service#context-and-capability-checks)

**Comment by dorispanos** [comment]
im starting to believe that i have uploaded an old version of the plugin for you to review. This was fixed 
![image](https://github.com/user-attachments/assets/4f31379b-1c75-438f-8a0e-61fe490a627f) I believe this is the correct way.

**Comment by volodymyrdovhan** [comment]
1. Please move classes/local/external to classes/external as it is part of the core modules.
2. Please add `self::validate_context($context);` for context validation to class pause_measure():
![image](https://github.com/user-attachments/assets/288de61d-2e2b-4c25-8e3d-ec062c6ff455)

**Comment by dorispanos** [comment]
Relocate back to class root the external folder adjust also namespace. Add self valdate to the service
![image](https://github.com/user-attachments/assets/9e522550-d3b3-4135-a5e1-3a61d96f1cb5)
