### ISSUE TITLE
Hardcoded parameters in sql queries

### ISSUE THREAD

**Issue by volodymyrdovhan** [WIDE-Services/ws_block_course_statistics_u#5]
Hello, 
There are a lot of hardcoded parameters in SQL queries in classes/dbquery.php.
All parameters should be implemented with placeholders.

Please review the documentation and requirements:
https://moodledev.io/general/community/plugincontribution/checklist#cross-db-compatibility

![image](https://github.com/user-attachments/assets/0cfc124f-a0ff-4398-bf87-f2cf872106f8)
![image](https://github.com/user-attachments/assets/b974edc7-58c8-4c83-859a-5bcad3beac75)

**Comment by dorispanos** [comment]
Yeah nothing to commit here. Now im 100% sure that i didnt correctly upload to moodle plugin directory the correct version of the plugin and you review an old one. im very sorry. that was fixed also->
![image](https://github.com/user-attachments/assets/8e930ffa-ce29-4f65-bf72-233e6eb1e237)
i believe this is the way. Same to all my queries.

**Comment by volodymyrdovhan** [comment]
These are still hardcoded parameters in db_course_activities_data, db_course_tools_data, db_user_exit_session and db_activity_title methods.

![image](https://github.com/user-attachments/assets/729ee0fd-7c16-4a42-8fa9-4cefc74fa5a9)

**Comment by dorispanos** [comment]
Change the harcoded data to db queries with param array on those methods.
![image](https://github.com/user-attachments/assets/9cfbae8c-3f77-48c5-8f9c-87998c1808ab)

**Comment by volodymyrdovhan** [comment]
@dorispanos please review db_user_exit_session() method:
![image](https://github.com/user-attachments/assets/21fae856-f258-4180-b420-dd84a7f11f86)

**Comment by dorispanos** [comment]
Im very sorry about that i forgot to modify the second query in method. I change it. I uploaded a new carsion 2020041073 with this modification.
![image](https://github.com/user-attachments/assets/7e05b355-8ea3-46b3-9b0b-6fd5da13d24a)
