### ISSUE TITLE
Missing license details, header and copyrights in JS and Mustache files

### ISSUE THREAD

**Issue by volodymyrdovhan** [WIDE-Services/ws_block_course_statistics_u#6]
Hello,
I found missing license details, header and copyrights in JS and Mustache files.
![image](https://github.com/user-attachments/assets/4ace117b-a7ac-496a-8d8c-ab4477232faf)
![image](https://github.com/user-attachments/assets/7a988cf3-f377-4aec-bb53-ed45cfad7e65)
![image](https://github.com/user-attachments/assets/e76b33ed-20bd-48e7-8a52-d4d478aecdac)

In addition missing context description in Mustache templates:
![image](https://github.com/user-attachments/assets/b36c281a-2657-4dc4-89fc-6d37542ce097)

**Comment by dorispanos** [comment]
I added all licence above js and mustache files and added description to mustache as well
![image](https://github.com/user-attachments/assets/92e7e525-2851-4142-8d8a-81fe6e38bdc9)
