### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by volodymyrdovhan** [WIDE-Services/ws_block_course_statistics_u#7]
Hello,

According to Moodle standards, all custom classes that are not part of the core API should be placed in the 'classes/local' folder to avoid potential namespace collisions. You can refer to the guidelines here:
[Namespace Collisions - Moodle Plugin Checklist](https://moodledev.io/general/community/plugincontribution/checklist#namespace-collisions)

Additionally, please review the rules for level 2 namespaces:
[Level 2 Namespaces](https://moodledev.io/general/development/policies/codingstyle#rules-for-level2)

All non core classes should be moved to classes/local:
![image](https://github.com/user-attachments/assets/105f2a22-87ff-4d6b-b615-66e297ad6ced)

**Comment by dorispanos** [comment]
I tranfered all non-core classes in the local directory and updated all namespaces in classes.
![image](https://github.com/user-attachments/assets/cc7f8a6f-a894-46f6-8060-df0cc2e8095f)
