### ISSUE TITLE
Incorrect plugin DB tables names

### ISSUE THREAD

**Issue by volodymyrdovhan** [WIDE-Services/ws_block_course_statistics_u#8]
Hello,

according to Moodle standards, all plugin tables names should be prefixed
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#table-names
https://moodledev.io/general/community/plugincontribution/checklist#namespace-collisions

For your plugin, all tables name should start with 'block_course_statistics_'

**Comment by dorispanos** [comment]
All tables starts with block_course_statistics_ in new version
![image](https://github.com/user-attachments/assets/9818c8c1-7fa7-4ddb-bf2a-4f94a9f4aa4a)
